function [fitresult, gof] = createFit(x, data)
%CREATEFIT(X,DATA)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jan-2019 20:28:19


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, data );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 2' );
% h = plot( fitresult, xData, yData );
% legend( h, 'data vs. x', 'untitled fit 2', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel data
% grid on


